### ISSUE TITLE
hardware-exporter crashes after connecting to redfish on Dell PowerEdge R740

### ISSUE THREAD

**Issue by peppepetra** [canonical/hardware-observer-operator#109]
After setting redfish credentials on hw-observer hardware-exporter stops collecting metrics and raise the following exception:

```
Nov 16 16:22:40 node-9 python3[3299197]: Traceback (most recent call last):
Nov 16 16:22:40 node-9 python3[3299197]:   File "/usr/lib/python3.10/wsgiref/handlers.py", line 137, in run
Nov 16 16:22:40 node-9 python3[3299197]:     self.result = application(self.environ, self.start_response)
Nov 16 16:22:40 node-9 python3[3299197]:   File "/var/lib/juju/agents/unit-hardware-observer-4/charm/venv/prometheus_client/exposition.py", line 128, in prometheus_app
Nov 16 16:22:40 node-9 python3[3299197]:     status, headers, output = _bake_output(registry, accept_header, accept_encoding_header, params, disable_compression)
Nov 16 16:22:40 node-9 python3[3299197]:   File "/var/lib/juju/agents/unit-hardware-observer-4/charm/venv/prometheus_client/exposition.py", line 104, in _bake_output
Nov 16 16:22:40 node-9 python3[3299197]:     output = encoder(registry)
Nov 16 16:22:40 node-9 python3[3299197]:   File "/var/lib/juju/agents/unit-hardware-observer-4/charm/venv/prometheus_client/openmetrics/exposition.py", line 21, in generate_latest
Nov 16 16:22:40 node-9 python3[3299197]:     for metric in registry.collect():
Nov 16 16:22:40 node-9 python3[3299197]:   File "/var/lib/juju/agents/unit-hardware-observer-4/charm/venv/prometheus_client/registry.py", line 97, in collect
Nov 16 16:22:40 node-9 python3[3299197]:     yield from collector.collect()
Nov 16 16:22:40 node-9 python3[3299197]:   File "/var/lib/juju/agents/unit-hardware-observer-4/charm/venv/prometheus_hardware_exporter/core.py", line 114, in collect
Nov 16 16:22:40 node-9 python3[3299197]:     payloads = self.fetch()
Nov 16 16:22:40 node-9 python3[3299197]:   File "/var/lib/juju/agents/unit-hardware-observer-4/charm/venv/prometheus_hardware_exporter/collector.py", line 972, in fetch
Nov 16 16:22:40 node-9 python3[3299197]:     ) = redfish_helper.get_storage_controller_data()
Nov 16 16:22:40 node-9 python3[3299197]:   File "/var/lib/juju/agents/unit-hardware-observer-4/charm/venv/prometheus_hardware_exporter/collectors/redfish.py", line 265, in get_storage_controller_data
Nov 16 16:22:40 node-9 python3[3299197]:     storage_controllers_list: List[Dict] = self.redfish_obj.get(curr_storage_uri).dict[
Nov 16 16:22:40 node-9 python3[3299197]: KeyError: 'StorageControllers'
```

**Comment by dashmage** [comment]
Fixed in [this commit](https://github.com/canonical/prometheus-hardware-exporter/commit/03a17a716f6c87153d4dadaeab25fb019dfee6dd) on prometheus-hardware-exporter.
