### ISSUE TITLE
SuperMicro storage controller KeyError

### ISSUE THREAD

**Issue by honghan-wong** [canonical/hardware-observer-operator#115]
We got an KeyError when deployed on Supermicro (H12DST-B) server

```
Traceback (most recent call last):
  File "/usr/lib/python3.8/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
  File "/var/lib/juju/agents/unit-hardware-observer-host-5/charm/venv/prometheus_client/exposition.py", line 128, in prometheus_app
    status, headers, output = _bake_output(registry, accept_header, accept_encoding_header, params, disable_compression)
  File "/var/lib/juju/agents/unit-hardware-observer-host-5/charm/venv/prometheus_client/exposition.py", line 104, in _bake_output
    output = encoder(registry)
  File "/var/lib/juju/agents/unit-hardware-observer-host-5/charm/venv/prometheus_client/openmetrics/exposition.py", line 21, in generate_latest
    for metric in registry.collect():
  File "/var/lib/juju/agents/unit-hardware-observer-host-5/charm/venv/prometheus_client/registry.py", line 97, in collect
    yield from collector.collect()
  File "/var/lib/juju/agents/unit-hardware-observer-host-5/charm/venv/prometheus_hardware_exporter/core.py", line 114, in collect
    payloads = self.fetch()
  File "/var/lib/juju/agents/unit-hardware-observer-host-5/charm/venv/prometheus_hardware_exporter/collector.py", line 972, in fetch
    ) = redfish_helper.get_storage_controller_data()
  File "/var/lib/juju/agents/unit-hardware-observer-host-5/charm/venv/prometheus_hardware_exporter/collectors/redfish.py", line 275, in get_storage_controller_data
    "controller_id": data["MemberId"],
KeyError: 'MemberId'
```

The output is as below from redfish API
```
curl -k -u 'user:pass' https://redfish.api/redfish/v1/Systems/1/Storage/NVMeSSD | jq
{
  "@odata.type": "#Storage.v1_7_1.Storage",
  "@odata.id": "/redfish/v1/Systems/1/Storage/NVMeSSD",
  "Id": "NVMeSSD",
  "Name": "NVMe Storage System",
  "StorageControllers": [
    {
      "@odata.id": "/redfish/v1/Systems/1/Storage/NVMeSSD#/StorageControllers/0",
      "MemberId": "0",
      "@odata.type": "#Storage.v1_7_1.StorageController",
      "FirmwareVersion": "00",
      "Status": {
        "State": "Enabled",
        "Health": "OK"
      },
      "Identifiers": [
        {
          "DurableName": ""
        }
      ],
      "SupportedControllerProtocols": [
        "PCIe"
      ],
      "SupportedDeviceProtocols": [
        "NVMe"
      ],
      "Oem": {}
    }
  ],
  "Drives": [
    {
      "@odata.id": "/redfish/v1/Chassis/NVMeSSD.0.Group.0.StorageBackplane/Drives/Disk.Bay.0"
    },
    {
      "@odata.id": "/redfish/v1/Chassis/NVMeSSD.0.Group.0.StorageBackplane/Drives/Disk.Bay.1"
    }
  ],
  "Volumes": {
    "@odata.id": "/redfish/v1/Systems/1/Storage/NVMeSSD/Volumes"
  },
  "Links": {
    "Enclosures": [
      {
        "@odata.id": "/redfish/v1/Chassis/NVMeSSD.0.Group.0.StorageBackplane"
      }
    ]
  },
  "Oem": {},
  "Description": "NVMe SSD",
  "Status": {
    "State": "Enabled",
    "Health": "OK"
  }
}
```

**Comment by honghan-wong** [comment]
the error has been by fixed https://github.com/canonical/prometheus-hardware-exporter/pull/71
