### ISSUE TITLE
Configure `redfish_client_timeout` with charm config

### ISSUE THREAD

**Issue by valexby** [canonical/hardware-observer-operator#170]
In environments where Redfish is slower to respond than 3 seconds, the hardware-observer fails to collect data and logs report
```
python3[3797165]: 2024-02-22 07:15:27 INFO User logged out: {"Success":{"code":"Base.v1_10_3.Success","Message":"Successfully Completed Request."}}
python3[3797165]: 2024-02-22 07:15:27 ERROR Exception occurred while getting redfish object:
python3[3797165]: Traceback (most recent call last):
python3[3797165]:   File "/var/lib/juju/agents/unit-hardware-observer-infra-2/charm/venv/urllib3/connectionpool.py", line 536, in _make_request
python3[3797165]:     response = conn.getresponse()
python3[3797165]:   File "/var/lib/juju/agents/unit-hardware-observer-infra-2/charm/venv/urllib3/connection.py", line 461, in getresponse
python3[3797165]:     httplib_response = super().getresponse()
python3[3797165]:   File "/var/lib/juju/agents/unit-hardware-observer-infra-2/charm/venv/urllib3/connection.py", line 461, in getresponse
python3[3797165]:     httplib_response = super().getresponse()
python3[3797165]:   File "/usr/lib/python3.10/http/client.py", line 1375, in getresponse
python3[3797165]:     response.begin()
python3[3797165]:   File "/usr/lib/python3.10/http/client.py", line 318, in begin
python3[3797165]:     version, status, reason = self._read_status()
python3[3797165]:   File "/usr/lib/python3.10/http/client.py", line 279, in _read_status
python3[3797165]:     line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
python3[3797165]:   File "/usr/lib/python3.10/socket.py", line 705, in readinto
python3[3797165]:     return self._sock.recv_into(b)
python3[3797165]:   File "/usr/lib/python3.10/ssl.py", line 1274, in recv_into
python3[3797165]:     return self.read(nbytes, buffer)
python3[3797165]:   File "/usr/lib/python3.10/ssl.py", line 1130, in read
python3[3797165]:     return self._sslobj.read(len, buffer)
python3[3797165]: TimeoutError: The read operation timed out
python3[3797165]: The above exception was the direct cause of the following exception:
python3[3797165]: Traceback (most recent call last):
python3[3797165]:   File "/var/lib/juju/agents/unit-hardware-observer-infra-2/charm/venv/requests/adapters.py", line 486, in send
python3[3797165]:     resp = conn.urlopen(
python3[3797165]:   File "/var/lib/juju/agents/unit-hardware-observer-infra-2/charm/venv/urllib3/connectionpool.py", line 844, in urlopen
python3[3797165]:     retries = retries.increment(
python3[3797165]:   File "/var/lib/juju/agents/unit-hardware-observer-infra-2/charm/venv/urllib3/util/retry.py", line 470, in increment
python3[3797165]:     raise reraise(type(error), error, _stacktrace)
python3[3797165]:   File "/var/lib/juju/agents/unit-hardware-observer-infra-2/charm/venv/urllib3/util/util.py", line 39, in reraise
python3[3797165]:     raise value
python3[3797165]:   File "/var/lib/juju/agents/unit-hardware-observer-infra-2/charm/venv/urllib3/connectionpool.py", line 790, in urlopen
python3[3797165]:     response = self._make_request(
python3[3797165]:   File "/var/lib/juju/agents/unit-hardware-observer-infra-2/charm/venv/urllib3/connectionpool.py", line 538, in _make_request
python3[3797165]:     self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
python3[3797165]:   File "/var/lib/juju/agents/unit-hardware-observer-infra-2/charm/venv/urllib3/connectionpool.py", line 370, in _raise_timeout
python3[3797165]:     raise ReadTimeoutError(
python3[3797165]: urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='10.169.128.2', port=443): Read timed out. (read timeout=3)
python3[3797165]: During handling of the above exception, another exception occurred:
python3[3797165]: Traceback (most recent call last):
python3[3797165]:   File "/var/lib/juju/agents/unit-hardware-observer-infra-2/charm/venv/redfish/rest/v1.py", line 910, in _rest_request
python3[3797165]:     resp = self._session.request(method.upper(), "{}{}".format(self.__base_url, reqpath), data=body,
python3[3797165]:   File "/var/lib/juju/agents/unit-hardware-observer-infra-2/charm/venv/requests/sessions.py", line 589, in request
python3[3797165]:     resp = self.send(prep, **send_kwargs)
python3[3797165]:   File "/var/lib/juju/agents/unit-hardware-observer-infra-2/charm/venv/requests/sessions.py", line 703, in send
python3[3797165]:     r = adapter.send(request, **kwargs)
python3[3797165]:   File "/var/lib/juju/agents/unit-hardware-observer-infra-2/charm/venv/requests/adapters.py", line 532, in send
python3[3797165]:     raise ReadTimeout(e, request=request)
python3[3797165]: requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='10.169.128.2', port=443): Read timed out. (read timeout=3)
python3[3797165]: The above exception was the direct cause of the following exception:
python3[3797165]: Traceback (most recent call last):
python3[3797165]:   File "/var/lib/juju/agents/unit-hardware-observer-infra-2/charm/venv/prometheus_hardware_exporter/collector.py", line 1016, in fetch
python3[3797165]:     ) = redfish_helper.get_storage_controller_data()
python3[3797165]:   File "/var/lib/juju/agents/unit-hardware-observer-infra-2/charm/venv/prometheus_hardware_exporter/collectors/redfish.py", line 276, in get_storage_co>
python3[3797165]:     system_resources = self.redfish_obj.get(
python3[3797165]:   File "/var/lib/juju/agents/unit-hardware-observer-infra-2/charm/venv/redfish/rest/v1.py", line 628, in get
python3[3797165]:     return self._rest_request(path, method='GET', args=args,
python3[3797165]:   File "/var/lib/juju/agents/unit-hardware-observer-infra-2/charm/venv/redfish/rest/v1.py", line 1110, in _rest_request
python3[3797165]:     return super(HttpClient, self)._rest_request(path=path, method=method,
python3[3797165]:   File "/var/lib/juju/agents/unit-hardware-observer-infra-2/charm/venv/redfish/rest/v1.py", line 954, in _rest_request
python3[3797165]:     raise RetriesExhaustedError() from cause_exception
python3[3797165]: redfish.rest.v1.RetriesExhaustedError
```

The default timeout is 3 seconds. It is quite strict and cannot be configured via charm configuration.
However, there is a configuration point in `/etc/hardware-exporter-config.yaml`
```
redfish_client_timeout: 10
```

Would be quite helpful to have this timeout configurable via charm config.

**Comment by Pjack** [comment]
@sudeephb , please confirm if this one is also covered by #193 ?

**Comment by sudeephb** [comment]
> @sudeephb , please confirm if this one is also covered by #193 ?

No, this needs to be taken care of separately. Even if we have a very long `collect_timeout`, redfish client timeout won't be changed, and it will timeout after 3 seconds.

**Comment by dashmage** [comment]
Couple of points to note here:
* The `collect_timeout` being configured in `/etc/hardware-exporter-config.yaml` is the timeout for collectors executing subprocess calls (eg: IPMI) and is NOT related to `redfish_client_timeout`. #193 only handles `collect_timeout`.
* @valexby I would like to know where you found the default redfish timeout to be 3 seconds. In prometheus-hardware-exporter, we [configure the default timeout to be 15s](https://github.com/canonical/prometheus-hardware-exporter/blob/main/prometheus_hardware_exporter/config.py#L16).
* If necessary, we can expose this as a modifiable charm config option with a reasonable default value.
