### ISSUE TITLE
Brief error state from failure to install ipmitool

### ISSUE THREAD

**Issue by dstathis** [canonical/hardware-observer-operator#64]
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-hob-0/charm/./src/charm.py", line 173, in <module>
    ops.main(HardwareObserverCharm)  # type: ignore
  File "/var/lib/juju/agents/unit-hob-0/charm/venv/ops/main.py", line 456, in __call__
    return main(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-hob-0/charm/venv/ops/main.py", line 441, in main
    _emit_charm_event(charm, dispatcher.event_name)
  File "/var/lib/juju/agents/unit-hob-0/charm/venv/ops/main.py", line 149, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-hob-0/charm/venv/ops/framework.py", line 344, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-hob-0/charm/venv/ops/framework.py", line 841, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-hob-0/charm/venv/ops/framework.py", line 930, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-hob-0/charm/./src/charm.py", line 60, in _on_install_or_upgrade
    redfish_creds = self._get_redfish_creds()
  File "/var/lib/juju/agents/unit-hob-0/charm/./src/charm.py", line 158, in _get_redfish_creds
    bmc_tools = bmc_hw_verifier()
  File "/var/lib/juju/agents/unit-hob-0/charm/src/hw_tools.py", line 309, in bmc_hw_verifier
    apt.add_package("ipmitool", update_cache=False)
  File "/var/lib/juju/agents/unit-hob-0/charm/lib/charms/operator_libs_linux/v0/apt.py", line 761, in add_package
    pkg, success = _add(p, version, arch)
  File "/var/lib/juju/agents/unit-hob-0/charm/lib/charms/operator_libs_linux/v0/apt.py", line 802, in _add
    pkg.ensure(state=PackageState.Present)
  File "/var/lib/juju/agents/unit-hob-0/charm/lib/charms/operator_libs_linux/v0/apt.py", line 289, in ensure
    self._add()
  File "/var/lib/juju/agents/unit-hob-0/charm/lib/charms/operator_libs_linux/v0/apt.py", line 261, in _add
    self._apt(
  File "/var/lib/juju/agents/unit-hob-0/charm/lib/charms/operator_libs_linux/v0/apt.py", line 255, in _apt
    raise PackageError(
charms.operator_libs_linux.v0.apt.PackageError: Could not install package(s) [['ipmitool=1.8.18-11ubuntu2.1']]: None

**Comment by dstathis** [comment]
The error state seems to clear up a few seconds later.

**Comment by Pjack** [comment]
Do you mind to provide more information about the environment? It may relate to the network status. 
Furthermore, what's the state of `juju status` ? thanks!

**Comment by Pjack** [comment]
No futher information, so we can close this issue
